-- Demo-only issue tracking for Consumer Copilot.
-- Run in Supabase SQL editor. Do not use real personal data.
create extension if not exists pgcrypto;

create table if not exists public.issues (
  id uuid primary key default gen_random_uuid(),
  reference_id text not null unique,
  device_id text not null,
  title text not null,
  category text not null,
  status text not null default 'submitted'
    check (status in ('submitted', 'under_review', 'awaiting_user_response', 'escalated', 'resolved', 'closed')),
  details jsonb not null default '{}'::jsonb,
  contact_preferences jsonb not null default '[]'::jsonb,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.issue_updates (
  id bigint generated by default as identity primary key,
  issue_id uuid not null references public.issues(id) on delete cascade,
  status text not null
    check (status in ('submitted', 'under_review', 'awaiting_user_response', 'escalated', 'resolved', 'closed')),
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists issues_device_updated_idx on public.issues (device_id, updated_at desc);
create index if not exists issue_updates_issue_created_idx on public.issue_updates (issue_id, created_at desc);

alter table public.issues enable row level security;
alter table public.issue_updates enable row level security;
-- Demo-only policies for the publishable key. Do not use these policies for real
-- personal data; replace them with Supabase Auth/RLS before production.
drop policy if exists "demo issues read" on public.issues;
create policy "demo issues read" on public.issues for select to anon using (true);
drop policy if exists "demo issues create" on public.issues;
create policy "demo issues create" on public.issues for insert to anon with check (true);
drop policy if exists "demo updates read" on public.issue_updates;
create policy "demo updates read" on public.issue_updates for select to anon using (true);
drop policy if exists "demo updates create" on public.issue_updates;
create policy "demo updates create" on public.issue_updates for insert to anon with check (true);
